language: node_js
node_js:
  - '4'
env:
  global:
    secure: mMWY4Yk0by921KmraMMvG6y/TKxTLvGI5sRiTtA4aqz/bgNLG4ZKMP/LQnrBoSzUSZDEIQm90jOP/bSnK2AkaQmRyh7sP6Y2yQWPgybmcpiRfc9ZaG0XnbQIfOtLVUUU5ITbwSgRltTCRRH1mup97WxOTI52rH1LVkDTTu1aIUnr9X0QSkZErb1wtPs8WAgOKIoZgPzTlCJBCjf32lt5gHOtWXHi5w9rgngkkHBPKKWpBa5mcaAmEJ/zV4tuBIUJEAVsOSKXOH9GomH/egmumEYq4aaxMVu0IrqsEmuUe1VEXzJC29RjKI8tF5N4qFV84VEkCulBEZTuY3wS9uiFcLFQA2uLyY3Fyna2+3YGhg9YXGQBG/7jGxZxELpZThNKLYUw/MeN7pV3uyUZKth061BOX9on2KRMdujWgUFBDkwtI0aEV/jeAgJ8fUteSRdBqlMclfzT6d5BElNbKd+uWYj23rUBekussKI46IMr6CDvhZwByUZyw0fKDcTWpRAhi9qK/A9E020bmvhf+BlcJkGmQGhaKXaSM+u/W5WNQw1I7PH9JXGILuDKVWTH80KiqF9zDM7o02gKE6ncDuzIlofmo0Zt5sAc0ZiwEdL7YOIi5lchOKEKZoNBclNwoozHB0t3HivtPuaTcp1/YDEJVc/w7oHCbwAf6LJTADmN0Io=
before_script:
  - npm install -g gulp jspm dtsm mocha
  - jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
  - npm install
  - jspm install
  - dtsm install
script:
  - mocha --compilers ts:espower-typescript/guess test/**/*.ts
  - gulp package
