language: node_js
node_js:
- '4'
env:
  global:
    secure: BRYFD6vk6RawhajcdHOlOKXE15ELhBiQG/sSyaZSoyoXQdEv7tkPRk3Cp2yEYBRCwe2l+sJ7Ow6+0bqBISO7JLtSNdOBI7YPC6YoS3a8S9pwzU+N+zZkplcSvURcxScxVQNYOVn6VCWSJixc/J3wgdzExYKlCxOrOtCRsAWn2UbjVUc1HnzLEc1uz94d/Mx/nmmWmQKVtzzOHB47Q4m4jrIVMYx+o1DzKs8xaJ16v4ITj2Xod8my7hViv9rCGaThUMm1PoPL2WKH3Hn+EaQaUZgQ1NC2gBoBdVQZLd5U82bZVp2K+VhAIncgflu90rN0iRwcNmy3yV2MoMpEjBZN2gdTL+LPqufgf91yKdOCIb5EliVosIKuAvj3CzF1DstCtxq1IGoljqNxIfK16RK+8p2M43lWDlj9yFlT/Smb0PNJEKVqD1jIrY9ogVQ3oHJAN6ppQkuYExKtqk6NB8owrmHv5qaSmzCVxDoqwVm7NOBWDWqP71oBUucf3uOT59WSy0ZTOF+Sx4D8HaVk+hvPf+aucGAyeGRcTWYKvh9QlF/XSatdykoEe5SMxIasamAu0xtmJyXgdCvCBpKg8pk6u2OWf+OWD5WFe1gTtKZSaqtfSta9PeuZV4O3CJoL1bJu0O1Wx8V1zJa7NBmBP7GBc6lzWfDRt1E8uOfpvIitkck=
before_script:
- npm install -g gulp jspm dtsm mocha
- jspm config registries.github.auth $GITHUB_OAUTH_TOKEN
- jspm install
- dtsm install
script:
- mocha --compilers ts:espower-typescript/guess test/**/*.ts
- gulp package
before_deploy:
- pushd release
- pushd darwin; zip -q ../esCalc-osx-x64.zip -r esCalc-darwin-x64; popd
- pushd win32; zip -q ../esCalc-win32-x64.zip -r esCalc-win32-x64; popd
- pushd linux; tar -jcf ../esCalc-linux-x64.tar.bz2 esCalc-linux-x64; popd
- popd
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
  - release/*.zip
  - release/*.tar.bz2
  on:
    tags: true
  skip_cleanup: true
cache:
  directories:
  - node_modules
  - src/jspm_packages
  - ".typings"
